---
model: "gpt-3.5-turbo" 

behavior:
  menu: "右のメニューからプロンプトを選んでね"
  subcommand_not_found: "サブコマンドが見つかりませんでした。"
  summarying: "<@{} が *{}* を選択したよ。ちょっと待ってね。考え中です...🍵"
  not_thread: ":warning: @summaru の呼び出しはスレッド内のみサポートされています。スレッドで呼び出してね!"
  unknown_command: "すいません コマンドがよくわかりませんでした"
  help: "スレッドで以下のコマンドを呼び出してください"
  default: "はい、なんでしょうか?"
