---
message:
  summarying: "ちょっと待ってね。考え中です...🍵"
  not_thread: ":warning: サマリ機能はスレッド内でのみサポートされています。スレッドで呼び出してね"
  unknown_command: "すいません コマンドがよくわかりませんでした"
  help: "help"
  default: "はい、なんでしょうか?"

prompts:
  default:
    title: "簡単な要約"
    query: |-
      このテキストの要約を作ってください。日本語でお願いします

  test:
    title: "感想を書いて"
    query: |-
      この文章を読んで、感想を書いてください