---
behavior:
  subcommand_not_found: "サブコマンドが見つかりませんでした。"
  summarying: "ちょっと待ってね。考え中です...🍵"
  not_thread: ":warning: @summaru の呼び出しはスレッド内のみサポートされています。スレッドで呼び出してね!"
  unknown_command: "すいません コマンドがよくわかりませんでした"
  help: "スレッドで以下のコマンドを呼び出してください"
  default: "はい、なんでしょうか?"