version: '3.8'

services:
  summaru:
    env_file: .env
    build:
      context: .
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./prompt.yaml:/app/prompt.yaml
    command: poetry run python bot.py
